name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install semantic-release@21.0.2 @semantic-release/git@10.0.1 semantic-release-replace-plugin@1.2.3
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SR_TOKEN }}
